spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:ecommerce}
    username: ${POSTGRES_USER:ecommerce}
    password: ${POSTGRES_PASSWORD:ecommerce}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
